# Generated by Django 3.0.2 on 2020-03-24 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='avail_stock',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='total_stock',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
