# Generated by Django 3.0.2 on 2020-03-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20200324_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuedbook',
            name='status',
            field=models.CharField(default='booked', max_length=10),
        ),
    ]
