# Generated by Django 3.0.2 on 2020-03-25 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_waitingtable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waitingtable',
            old_name='User',
            new_name='users',
        ),
    ]
