# Generated by Django 3.0.2 on 2020-03-25 12:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0006_admintemp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminTemp',
            new_name='LibrarianTemp',
        ),
    ]
